/*
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.ide


/**
 * Use this class to register ide components.
 */
class MathCompilerDslIdeModule extends AbstractMathCompilerDslIdeModule {
}
