/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.mathCompilerDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assignment.mathCompilerDsl.MathExp#getExpName <em>Exp Name</em>}</li>
 *   <li>{@link org.xtext.assignment.mathCompilerDsl.MathExp#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getMathExp()
 * @model
 * @generated
 */
public interface MathExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp Name</em>' attribute.
   * @see #setExpName(String)
   * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getMathExp_ExpName()
   * @model
   * @generated
   */
  String getExpName();

  /**
   * Sets the value of the '{@link org.xtext.assignment.mathCompilerDsl.MathExp#getExpName <em>Exp Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp Name</em>' attribute.
   * @see #getExpName()
   * @generated
   */
  void setExpName(String value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getMathExp_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link org.xtext.assignment.mathCompilerDsl.MathExp#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // MathExp
