/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.mathCompilerDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Lang</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assignment.mathCompilerDsl.MathLang#getMathList <em>Math List</em>}</li>
 * </ul>
 *
 * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getMathLang()
 * @model
 * @generated
 */
public interface MathLang extends EObject
{
  /**
   * Returns the value of the '<em><b>Math List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.assignment.mathCompilerDsl.MathExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Math List</em>' containment reference list.
   * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getMathLang_MathList()
   * @model containment="true"
   * @generated
   */
  EList<MathExp> getMathList();

} // MathLang
