/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.mathCompilerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assignment.mathCompilerDsl.Var#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getVar()
 * @model
 * @generated
 */
public interface Var extends VariableUse
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Let)
   * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getVar_Ref()
   * @model
   * @generated
   */
  Let getRef();

  /**
   * Sets the value of the '{@link org.xtext.assignment.mathCompilerDsl.Var#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Let value);

} // Var
