/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.mathCompilerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Use</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getVariableUse()
 * @model
 * @generated
 */
public interface VariableUse extends Expression
{
} // VariableUse
