/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.mathCompilerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage#getVariableBinding()
 * @model
 * @generated
 */
public interface VariableBinding extends Expression
{
} // VariableBinding
