/*
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathCompilerDslScopeProvider extends DelegatingScopeProvider {
}
