/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment;

import org.xtext.assignment.AbstractMathCompilerDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathCompilerDslRuntimeModule extends AbstractMathCompilerDslRuntimeModule {
}
