/*
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.assignment.parser.antlr.internal.InternalMathCompilerDslParser;
import org.xtext.assignment.services.MathCompilerDslGrammarAccess;

public class MathCompilerDslParser extends AbstractAntlrParser {

	@Inject
	private MathCompilerDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathCompilerDslParser createParser(XtextTokenStream stream) {
		return new InternalMathCompilerDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MathLang";
	}

	public MathCompilerDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathCompilerDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
