/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.validation;

import org.xtext.assignment.validation.AbstractMathCompilerDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MathCompilerDslValidator extends AbstractMathCompilerDslValidator {
}
