/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.mathCompilerDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage;
import org.xtext.assignment.mathCompilerDsl.MathExp;
import org.xtext.assignment.mathCompilerDsl.MathLang;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Math Lang</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.assignment.mathCompilerDsl.impl.MathLangImpl#getMathList <em>Math List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MathLangImpl extends MinimalEObjectImpl.Container implements MathLang
{
  /**
   * The cached value of the '{@link #getMathList() <em>Math List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMathList()
   * @generated
   * @ordered
   */
  protected EList<MathExp> mathList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MathLangImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathCompilerDslPackage.Literals.MATH_LANG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MathExp> getMathList()
  {
    if (mathList == null)
    {
      mathList = new EObjectContainmentEList<MathExp>(MathExp.class, this, MathCompilerDslPackage.MATH_LANG__MATH_LIST);
    }
    return mathList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MathCompilerDslPackage.MATH_LANG__MATH_LIST:
        return ((InternalEList<?>)getMathList()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MathCompilerDslPackage.MATH_LANG__MATH_LIST:
        return getMathList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MathCompilerDslPackage.MATH_LANG__MATH_LIST:
        getMathList().clear();
        getMathList().addAll((Collection<? extends MathExp>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MathCompilerDslPackage.MATH_LANG__MATH_LIST:
        getMathList().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MathCompilerDslPackage.MATH_LANG__MATH_LIST:
        return mathList != null && !mathList.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MathLangImpl
