/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.ui.contentassist;

import org.xtext.assignment.ui.contentassist.AbstractMathCompilerDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MathCompilerDslProposalProvider extends AbstractMathCompilerDslProposalProvider {
}
