/*
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathCompilerDslStandaloneSetup extends MathCompilerDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MathCompilerDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
