/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.ide;

import org.xtext.assignment.ide.AbstractMathCompilerDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathCompilerDslIdeModule extends AbstractMathCompilerDslIdeModule {
}
