/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.assignment.MathCompilerDslRuntimeModule;
import org.xtext.assignment.MathCompilerDslStandaloneSetup;
import org.xtext.assignment.ide.MathCompilerDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathCompilerDslIdeSetup extends MathCompilerDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathCompilerDslRuntimeModule _mathCompilerDslRuntimeModule = new MathCompilerDslRuntimeModule();
    MathCompilerDslIdeModule _mathCompilerDslIdeModule = new MathCompilerDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathCompilerDslRuntimeModule, _mathCompilerDslIdeModule));
  }
}
