/**
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.xtext.assignment.ui.AbstractMathCompilerDslUiModule;
import org.xtext.assignment.ui.hover.MathHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MathCompilerDslUiModule extends AbstractMathCompilerDslUiModule {
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
    return MathHoverProvider.class;
  }
  
  public MathCompilerDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
