/*
 * generated by Xtext 2.24.0
 */
package org.xtext.assignment.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.assignment.mathCompilerDsl.Div;
import org.xtext.assignment.mathCompilerDsl.Let;
import org.xtext.assignment.mathCompilerDsl.MathCompilerDslPackage;
import org.xtext.assignment.mathCompilerDsl.MathExp;
import org.xtext.assignment.mathCompilerDsl.MathLang;
import org.xtext.assignment.mathCompilerDsl.Minus;
import org.xtext.assignment.mathCompilerDsl.Mult;
import org.xtext.assignment.mathCompilerDsl.Plus;
import org.xtext.assignment.mathCompilerDsl.Var;
import org.xtext.assignment.services.MathCompilerDslGrammarAccess;

@SuppressWarnings("all")
public class MathCompilerDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MathCompilerDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MathCompilerDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MathCompilerDslPackage.DIV:
				sequence_Factor(context, (Div) semanticObject); 
				return; 
			case MathCompilerDslPackage.LET:
				sequence_VariableBinding(context, (Let) semanticObject); 
				return; 
			case MathCompilerDslPackage.MATH_EXP:
				sequence_MathExp(context, (MathExp) semanticObject); 
				return; 
			case MathCompilerDslPackage.MATH_LANG:
				sequence_MathLang(context, (MathLang) semanticObject); 
				return; 
			case MathCompilerDslPackage.MINUS:
				sequence_Exp(context, (Minus) semanticObject); 
				return; 
			case MathCompilerDslPackage.MULT:
				sequence_Factor(context, (Mult) semanticObject); 
				return; 
			case MathCompilerDslPackage.NUMBER:
				sequence_Number(context, (org.xtext.assignment.mathCompilerDsl.Number) semanticObject); 
				return; 
			case MathCompilerDslPackage.PLUS:
				sequence_Exp(context, (Plus) semanticObject); 
				return; 
			case MathCompilerDslPackage.VAR:
				sequence_VariableUse(context, (Var) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Exp returns Minus
	 *     Exp.Plus_1_0_0_1 returns Minus
	 *     Exp.Minus_1_0_1_1 returns Minus
	 *     Factor returns Minus
	 *     Factor.Mult_1_0_0_1 returns Minus
	 *     Factor.Div_1_0_1_1 returns Minus
	 *     Primary returns Minus
	 *     Parenthesis returns Minus
	 *
	 * Constraint:
	 *     (left=Exp_Minus_1_0_1_1 right=Factor)
	 */
	protected void sequence_Exp(ISerializationContext context, Minus semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.MINUS__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.MINUS__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.MINUS__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.MINUS__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExpAccess().getMinusLeftAction_1_0_1_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getExpAccess().getRightFactorParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Plus
	 *     Exp.Plus_1_0_0_1 returns Plus
	 *     Exp.Minus_1_0_1_1 returns Plus
	 *     Factor returns Plus
	 *     Factor.Mult_1_0_0_1 returns Plus
	 *     Factor.Div_1_0_1_1 returns Plus
	 *     Primary returns Plus
	 *     Parenthesis returns Plus
	 *
	 * Constraint:
	 *     (left=Exp_Plus_1_0_0_1 right=Factor)
	 */
	protected void sequence_Exp(ISerializationContext context, Plus semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.PLUS__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.PLUS__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.PLUS__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.PLUS__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExpAccess().getPlusLeftAction_1_0_0_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getExpAccess().getRightFactorParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Div
	 *     Exp.Plus_1_0_0_1 returns Div
	 *     Exp.Minus_1_0_1_1 returns Div
	 *     Factor returns Div
	 *     Factor.Mult_1_0_0_1 returns Div
	 *     Factor.Div_1_0_1_1 returns Div
	 *     Primary returns Div
	 *     Parenthesis returns Div
	 *
	 * Constraint:
	 *     (left=Factor_Div_1_0_1_1 right=Primary)
	 */
	protected void sequence_Factor(ISerializationContext context, Div semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.DIV__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.DIV__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.DIV__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.DIV__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFactorAccess().getDivLeftAction_1_0_1_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getFactorAccess().getRightPrimaryParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Mult
	 *     Exp.Plus_1_0_0_1 returns Mult
	 *     Exp.Minus_1_0_1_1 returns Mult
	 *     Factor returns Mult
	 *     Factor.Mult_1_0_0_1 returns Mult
	 *     Factor.Div_1_0_1_1 returns Mult
	 *     Primary returns Mult
	 *     Parenthesis returns Mult
	 *
	 * Constraint:
	 *     (left=Factor_Mult_1_0_0_1 right=Primary)
	 */
	protected void sequence_Factor(ISerializationContext context, Mult semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.MULT__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.MULT__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.MULT__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.MULT__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFactorAccess().getMultLeftAction_1_0_0_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getFactorAccess().getRightPrimaryParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     MathExp returns MathExp
	 *
	 * Constraint:
	 *     (expName=STRING exp=Exp)
	 */
	protected void sequence_MathExp(ISerializationContext context, MathExp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.MATH_EXP__EXP_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.MATH_EXP__EXP_NAME));
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.MATH_EXP__EXP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.MATH_EXP__EXP));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMathExpAccess().getExpNameSTRINGTerminalRuleCall_1_0(), semanticObject.getExpName());
		feeder.accept(grammarAccess.getMathExpAccess().getExpExpParserRuleCall_3_0(), semanticObject.getExp());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     MathLang returns MathLang
	 *
	 * Constraint:
	 *     (mathList+=MathExp mathList+=MathExp*)
	 */
	protected void sequence_MathLang(ISerializationContext context, MathLang semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Number
	 *     Exp.Plus_1_0_0_1 returns Number
	 *     Exp.Minus_1_0_1_1 returns Number
	 *     Factor returns Number
	 *     Factor.Mult_1_0_0_1 returns Number
	 *     Factor.Div_1_0_1_1 returns Number
	 *     Primary returns Number
	 *     Parenthesis returns Number
	 *     Number returns Number
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_Number(ISerializationContext context, org.xtext.assignment.mathCompilerDsl.Number semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.NUMBER__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.NUMBER__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNumberAccess().getValueINTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Let
	 *     Exp.Plus_1_0_0_1 returns Let
	 *     Exp.Minus_1_0_1_1 returns Let
	 *     Factor returns Let
	 *     Factor.Mult_1_0_0_1 returns Let
	 *     Factor.Div_1_0_1_1 returns Let
	 *     Primary returns Let
	 *     VariableBinding returns Let
	 *     Parenthesis returns Let
	 *
	 * Constraint:
	 *     (name=ID binding=Exp body=Exp)
	 */
	protected void sequence_VariableBinding(ISerializationContext context, Let semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.LET__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.LET__NAME));
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.LET__BINDING) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.LET__BINDING));
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.LET__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.LET__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableBindingAccess().getNameIDTerminalRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getVariableBindingAccess().getBindingExpParserRuleCall_4_0(), semanticObject.getBinding());
		feeder.accept(grammarAccess.getVariableBindingAccess().getBodyExpParserRuleCall_6_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Var
	 *     Exp.Plus_1_0_0_1 returns Var
	 *     Exp.Minus_1_0_1_1 returns Var
	 *     Factor returns Var
	 *     Factor.Mult_1_0_0_1 returns Var
	 *     Factor.Div_1_0_1_1 returns Var
	 *     Primary returns Var
	 *     VariableUse returns Var
	 *     Parenthesis returns Var
	 *
	 * Constraint:
	 *     ref=[Let|ID]
	 */
	protected void sequence_VariableUse(ISerializationContext context, Var semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerDslPackage.Literals.VAR__REF) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerDslPackage.Literals.VAR__REF));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableUseAccess().getRefLetIDTerminalRuleCall_1_0_1(), semanticObject.eGet(MathCompilerDslPackage.Literals.VAR__REF, false));
		feeder.finish();
	}
	
	
}
